from optimization_functions.optimization_functions import (
    levy_function,
    rosenbrock_function,
    zakharov_function,
)

RESULT_FILE = "mvmo_comparison.log"
SEED = 42
POPULATIONS = 30
POPULATIONS_SIZES = [10, 40, 70]
DIMENSIONS = 6
MUTATION_SIZE = 1

POP_SIZE_ITERATIONS = {
    10: 20000,
    40: 5000,
    70: 2857
}

TYPICAL_BOUNDARIES = (-10, 10)
TYPICAL_LIST_BOUNDARIES = [
    (TYPICAL_BOUNDARIES[0], TYPICAL_BOUNDARIES[1]) for _ in range(DIMENSIONS)
]

LEVY_BOUNDARIES = ROSENBROCK_BOUNDARIES = ZAKHAROV_BOUNDARIES = TYPICAL_BOUNDARIES
LEVY_LIST_BOUNDARIES = ROSENBROCK_LIST_BOUNDARIES = ZAKHAROV_LIST_BOUNDARIES = (
    TYPICAL_LIST_BOUNDARIES
)

COMPARISON_FUNCTIONS = [levy_function, rosenbrock_function, zakharov_function]
COMPARISON_BOUNDARIES = [LEVY_BOUNDARIES, ROSENBROCK_BOUNDARIES, ZAKHAROV_BOUNDARIES]
COMPARISON_LIST_BOUNDARIES = [
    LEVY_LIST_BOUNDARIES,
    ROSENBROCK_LIST_BOUNDARIES,
    ZAKHAROV_LIST_BOUNDARIES,
]
